title: SKY Higher ✈️
description: Thinking first, Coding next.
author: Sung-Kyu Yoo
github: https://github.com/skyoo2003
about: Developer at Kakao
avatar_url: /static/img/avatar.jpg
google_analytics: UA-85297310-1
google_ad_client: ca-pub-7498978308301601

enableTags: true
tagarray: []

social:
    # - icon: fa-linkedin
    #   link: "#"

share:
 fb_appid: 1112332078820931

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /category/
    - text: Github
      url: https://github.com/skyoo2003
    - text: XML Feed
      url: /feed.xml

url: "https://skyoo2003.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
