title: Today I Learned
description: TIL, a small contribution to the world
author: Sung-Kyu Yoo
github: https://github.com/skyoo2003
about: Search service developer.
avatar_url: /static/img/avatar.jpg
disqus_shortname: todayilearned
google_analytics: UA-85297310-1
google_ad_client: ca-pub-7498978308301601

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    #- icon: fa-skype
    #  link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/mr_skyoo"
    # - icon: fa-linkedin
    #   link: "#"
    #- icon: fa-stack-exchange
    #  link: "#"

share:
 twitter_username: mr_skyoo
 fb_appid: 1112332078820931

urls:
    - text: About Me
      url: /about/
    - text: Project
      url: /project/
    - text: Category
      url: /category/
    - text: Github
      url: https://github.com/skyoo2003
    - text: XML Feed
      url: /feed.xml

url: "https://skyoo2003.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
