title: Today I Learned
description: TIL, a small contribution to the world
author: Sung-Kyu Yoo
github: https://github.com/skyoo2003
about: Search service developer.
disqus_shortname: tilascttw
google_analytics: UA-85297310-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    #- icon: fa-skype
    #  link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    #- icon: fa-stack-exchange
    #  link: "#"

share:
 twitter_username: mr_skyoo
 fb_appid: 1112332078820931

urls:
    - text: About Me
      url: /about/
    # - text: Project
    #   url: /project/
    - text: Category
      url: /category/
    - text: Github
      url: https://github.com/skyoo2003
    - text: XML Feed
      url: /feed.xml

url: "https://skyoo2003.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
