title: 📚 Devlog in the SKY 📚
description: Yet another developer's blog
author: Sung-Kyu Yoo
github: https://github.com/skyoo2003
about: Software Developer
avatar_url: /static/img/avatar.jpg
google_analytics: UA-85297310-1
google_ad_client: ca-pub-7498978308301601

social:
    - icon: fa-github-alt
      link: "https://github.com/skyoo2003"
    - icon: fa-linkedin   
      link: "https://www.linkedin.com/in/성규-유-6b2251b7"

share:
 fb_appid: 1112332078820931

urls:
    - text: About Me
      url: /about/
    - text: Category
      url: /category/
    - text: XML Feed
      url: /feed.xml

url: "https://skyoo2003.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
